---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Jellyfin Stack:
    - Jellyfin - Core:
        icon: /images/jellyfin_logo.png
        href: http://192.168.0.124:8096/web/index.html#/home.html
        description: Main Servathan Jellyfin instance

- Servathan-pi:
    - Cheat Sheet:
        href: https://tinyurl.com/danelinuxcheatsheet
        description: Linux google doc notes

    - Personal Homepage:
        href: http://192.168.0.235:8000/
        description: Raw HTML homepage (flask test)
    - This:
        href: http://192.168.0.235:3000/
        description: Recursive recursion .......
