---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Jellyfin Stack:
    - Jellyfin - Core:
        href: http://192.168.0.124:8096/web/index.html#/home.html
        description: Main Servathan Jellyfin instance

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
