---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Jellyfin Stack:
    - Jellyfin - Core:
        href: http://192.168.0.124:8096/web/index.html#/home.html
        description: Main Servathan Jellyfin instance

- Servathan-pi:
    - Personal Homepage:
        href: http://192.168.0.235:8000/
        description: Raw HTML homepage (flask test)
    - This:
        href: http://192.168.0.235:3000/
        description: Recursive recursion .......

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
